"""Persistent state package — re-exports the full public API for backward compatibility."""
from __future__ import annotations

# Core constants and helpers
from ._core import (
    PBKDF2_ROUNDS,
    DEFAULT_AUTO_COMPACT_THRESHOLD_LEFT_PERCENT,
    DEFAULT_PENDING_INPUT_LIMIT,
    DEFAULT_SESSION_GROUP,
    SESSION_GROUP_DEFAULT_PERMISSIONS,
    normalize_auto_compact_threshold_left_percent,
    normalize_username,
    hash_password,
    digest_token,
    history_state_key,
    codex_session_key,
    claude_session_key,
    agent_state_key,
    state_dir,
    sessions_dir,
    session_user_dir,
    session_dir,
    session_pending_dir,
    session_services_dir,
    session_goal_manager_dir,
    session_dag_dir,
    session_metadata_path,
    session_timeline_path,
    session_pending_path,
    session_goal_manager_pending_path,
    session_service_pending_path,
    session_service_state_path,
    session_goal_manager_state_path,
    session_goal_manager_reviews_path,
    session_dag_parents_path,
    session_dag_children_path,
    session_agent_state_path,
    state_path,
    lock_path,
    state_lock,
    state_read_lock,
    write_state,
    write_json_file,
    read_json_file,
    append_jsonl,
    read_jsonl,
    write_jsonl,
    remove_file_if_exists,
    _load_state_unlocked,
    ensure_session_storage_unlocked,
    ensure_state,
)

# Auth
from .auth import (
    has_users,
    create_user,
    bootstrap_root_user,
    verify_user_password,
    create_session,
    resolve_session,
    resolve_session_context,
    delete_session,
)

# History / pending inputs
from .history import (
    append_history,
    get_history,
    history_subscriber_key,
    register_history_subscriber,
    unregister_history_subscriber,
    service_pending_state_key,
    append_pending_input,
    append_service_pending_input,
    load_pending_inputs,
    load_service_pending_inputs,
    clear_pending_inputs,
    drain_pending_inputs,
    drain_service_pending_inputs,
    append_goal_manager_pending_input,
    load_goal_manager_pending_inputs,
    drain_goal_manager_pending_inputs,
)

# Provider sessions
from .provider_session import (
    load_claude_session,
    save_claude_session,
    list_claude_sessions,
    load_codex_session,
    list_codex_sessions,
    save_codex_session,
)

# Conversation sessions
from .conversation import (
    list_sessions,
    list_sessions_with_histories,
    list_all_sessions_with_users,
    list_sessions_bound_to_service,
    create_conversation_session,
    get_session_service,
    lease_session_service,
    release_session_service,
    release_nonrunnable_session_services,
    get_session_settings,
    update_session_auto_compact_threshold,
    update_session_goal,
    update_session_goal_flags,
    schedule_session_auto_resume,
    consume_session_due_auto_resume,
    update_session_context_status,
    record_session_agent_contact,
    list_session_agent_contacts,
    resolve_session_agent_id,
    update_goal_manager_review_cursor,
    list_session_parents,
    list_session_children,
    add_session_child,
    complete_session_child,
    create_child_conversation_session,
    rename_session,
    select_session,
    session_group_permissions,
    session_operation_allowed,
)

# Agent audit
from .agent_audit import (
    load_agent_audit_state,
    save_agent_audit_state,
    reset_agent_audit_states_for_session,
)

__all__ = [
    # Core constants
    "PBKDF2_ROUNDS",
    "DEFAULT_AUTO_COMPACT_THRESHOLD_LEFT_PERCENT",
    "DEFAULT_PENDING_INPUT_LIMIT",
    "DEFAULT_SESSION_GROUP",
    "SESSION_GROUP_DEFAULT_PERMISSIONS",
    # Core helpers
    "normalize_auto_compact_threshold_left_percent",
    "normalize_username",
    "hash_password",
    "digest_token",
    "history_state_key",
    "codex_session_key",
    "claude_session_key",
    "agent_state_key",
    "state_dir",
    "sessions_dir",
    "session_user_dir",
    "session_dir",
    "session_pending_dir",
    "session_services_dir",
    "session_goal_manager_dir",
    "session_dag_dir",
    "session_metadata_path",
    "session_timeline_path",
    "session_pending_path",
    "session_goal_manager_pending_path",
    "session_service_pending_path",
    "session_service_state_path",
    "session_goal_manager_state_path",
    "session_goal_manager_reviews_path",
    "session_dag_parents_path",
    "session_dag_children_path",
    "session_agent_state_path",
    "state_path",
    "lock_path",
    "state_lock",
    "state_read_lock",
    "write_state",
    "write_json_file",
    "read_json_file",
    "append_jsonl",
    "read_jsonl",
    "write_jsonl",
    "remove_file_if_exists",
    "_load_state_unlocked",
    "ensure_session_storage_unlocked",
    "ensure_state",
    # Auth
    "has_users",
    "create_user",
    "bootstrap_root_user",
    "verify_user_password",
    "create_session",
    "resolve_session",
    "resolve_session_context",
    "delete_session",
    # History
    "append_history",
    "get_history",
    "history_subscriber_key",
    "register_history_subscriber",
    "unregister_history_subscriber",
    "service_pending_state_key",
    "append_pending_input",
    "append_service_pending_input",
    "load_pending_inputs",
    "load_service_pending_inputs",
    "clear_pending_inputs",
    "drain_pending_inputs",
    "drain_service_pending_inputs",
    "append_goal_manager_pending_input",
    "load_goal_manager_pending_inputs",
    "drain_goal_manager_pending_inputs",
    # Provider sessions
    "load_claude_session",
    "save_claude_session",
    "list_claude_sessions",
    "load_codex_session",
    "list_codex_sessions",
    "save_codex_session",
    # Conversation sessions
    "list_sessions",
    "list_sessions_with_histories",
    "list_all_sessions_with_users",
    "list_sessions_bound_to_service",
    "create_conversation_session",
    "get_session_service",
    "lease_session_service",
    "release_session_service",
    "release_nonrunnable_session_services",
    "get_session_settings",
    "update_session_auto_compact_threshold",
    "update_session_goal",
    "update_session_goal_flags",
    "schedule_session_auto_resume",
    "consume_session_due_auto_resume",
    "update_session_context_status",
    "record_session_agent_contact",
    "list_session_agent_contacts",
    "resolve_session_agent_id",
    "update_goal_manager_review_cursor",
    "list_session_parents",
    "list_session_children",
    "add_session_child",
    "complete_session_child",
    "create_child_conversation_session",
    "rename_session",
    "select_session",
    "session_group_permissions",
    "session_operation_allowed",
    # Agent audit
    "load_agent_audit_state",
    "save_agent_audit_state",
    "reset_agent_audit_states_for_session",
]
